# Generated by Django 5.0.3 on 2024-05-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycvvv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
    ]
