# Generated by Django 5.0.3 on 2024-05-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycvvv', '0002_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsetting',
            old_name='parameters',
            new_name='parameter',
        ),
    ]
